#!/usr/bin/env bash
# Summary: List existing plenv shims
# Usage: plenv shims [--short]

set -e
[[ -n "$PLENV_DEBUG" ]] && set -x

# Provide plenv completions
if [[ "$1" = "--complete" ]]; then
  echo --short
  exit
fi

if [[ "$1" = "--short" ]]; then
  command -p ls -1N "$PLENV_ROOT"/shims
else
  command -p ls -1N "$PLENV_ROOT"/shims/*
fi
